name: ci
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  python:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: signer } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install --upgrade pip ruff bandit
      - run: ruff check . || true
      - run: bandit -q -r . || true

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify site files exist
        run: |
          test -f site/demo-embed.html
          test -f site/verify.html
          echo "Site sanity OK"
