name: ci
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sanity check site files
        shell: bash
        run: |
          set -e
          # Accept either root or site/ layout to be robust
          if [ -f demo-embed.html ]; then
            echo "Found root-level pages."
            test -f demo-embed.html
            test -f verify.html
          elif [ -f site/demo-embed.html ]; then
            echo "Found site/ pages."
            test -f site/demo-embed.html
            test -f site/verify.html
          else
            echo "Could not find demo-embed.html or verify.html" >&2
            exit 1
          fi
          echo "Site sanity OK."
